# Companion radio config file

# This file is in TOML format
# https://toml.io/en/

# This sample config file just configures a fake interface
interfaces = ["mock"]

# And a single companion radio with a randomly-generated key
devices = ["companion"]


[dispatcher]
pass_internal = true

# Interfaces

# Waveshare LoRa HAT
[interface.waveshare]

# What kind of interface is this?
type="lora"

# UK/EU default
frequency=869618000
sf=8
bw=62500
cr=8
txpower=22

# Use DIO2 as RF switch
dio2.rfswitch = true

# HT-RA62 module wired to a Raspberry Pi
[interface.htra62]

type="lora"

# UK/EU default
frequency=869618000
sf=8
bw=62500
cr=8
txpower=22

# Use DIO3 to control TXCO
# Valid voltages are: 1.6, 1.7, 1.8, 2.2, 2.4, 2.7, 3.0, 3.3
dio3.voltage = 1.8
# Valid delay values are 2.5, 5, 10
dio3.tcxo_delay = 10


[interface.espnow]
# Interface name
device = "mon0"

[interface.mock]
# Optional file to read from; if not specified, the mock interface is just
# a null source/sink
#file="mock.txt"

[interface.companion]
# Default connection is /dev/ttyUSB0
# port = "/dev/ttyUSB0"


[device.companion]
# What kind of device is this? Defaults to the device name
# type = "companion"

# Default name is "Companion ########" (8 bytes of public key)
# name = "New companion radio"

# Default is to create a new private/public key
# Both 32-byte (64 hex characters) and 64-byte (128 hex characters)
# private keys are supported
# privatekey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Default is no latitude/longitude
# lat = 0
# lon = 0

# Contacts file
contacts = "contacts.mesh"

# Maximum channels
# channels = 32
channelfile = "channels.json"

# Make sure the Public channel is there
add_public_channel = true

interface = "wifi"
# wifi.port = 5000
# wifi.listen = all interfaces

# interface = "serial"
# serial.port = "/dev/tnt0"

